### ISSUE TITLE
[ENH] p val image 

### ISSUE THREAD

**Issue by sattertt** [PennLINC/ConFixel#20]
writing p val images as 1-p will make them much easier to view/threshold.

**Comment by zhao-cy** [comment]
transferred this issue to ConFixel repo

**Comment by zhao-cy** [comment]
Tests:
- convoxel's volume write function: 
  - with PNC fMRI n-back: randomly selected a pair of p.value and 1m.p.value (fdr and raw p-value) and randomly picked voxels and checked the values are expected (sum of 1) in MRView
