### ISSUE TITLE
Convoxel KeyError

### ISSUE THREAD

**Issue by ClementGuichet** [PennLINC/ConFixel#37]
Hi, 

I'm getting a KeyError: 'source_file' when running the convoxel command although the input csv is organized according to the doc. Am I missing something ?

![image](https://github.com/PennLINC/ConFixel/assets/120226253/7db24105-cbad-4a32-a506-a902838da242)

**Comment by ClementGuichet** [comment]
Yes exactly, I followed the markdown. I'm running ConVoxel on WSL which is prone to error, I may try on my Linux machine if this doesn't work out.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Clement/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Clement/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">


scalar_name | source_file | source_mask_file | subject_id | age
-- | -- | -- | -- | --
TW_FA | ./TW_FA/sub_1.nii | ./TW_FA_Gaussian70_155subj_mean_mask.nii | sub_1 | 45
TW_FA | ./TW_FA/sub_2.nii | ./TW_FA_Gaussian70_155subj_mean_mask.nii | sub_2 | 47
TW_FA | ./TW_FA/sub_3.nii | ./TW_FA_Gaussian70_155subj_mean_mask.nii | sub_3 | 48



</body>

</html>

**Comment by ClementGuichet** [comment]
**Issue resolved**

The KeyError was due to a weird encoding by excel when exporting to csv format (semicolon instead of commas). It worked fine after importing and writing out a new csv file via R.

Thanks for your help !

**Comment by zhao-cy** [comment]
Oh wow, that's a great catch and thank you for sharing this with me!

Cheers,
Chenying
